/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package foodxyz;
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Adam
 */
public class adminLaporan extends javax.swing.JFrame {

    Statement stat;
    ResultSet rs;
    String sql;
    Connection kon;
    private DefaultTableModel daftartabel;
    
    public adminLaporan() {
        initComponents();
        FoodXYZ DB = new FoodXYZ();
        DB.konfig();
        kon = DB.con;
        stat = DB.stm;
        this.listLaporan();
    }
// menampilkan data yang ada di tabel transaksi
    public void listLaporan() {
        daftartabel = new DefaultTableModel();
        daftartabel.addColumn("id");
        daftartabel.addColumn("tanggal transaksi");
        daftartabel.addColumn("total bayar");
        daftartabel.addColumn("id user");
        daftartabel.addColumn("nama kasir");
        list.setModel(daftartabel);
        FoodXYZ list = new FoodXYZ();
        list.konfig(); 
        Connection kon = list.getConnection(); 
        try{
            stat = kon.createStatement();
            sql = "SELECT * FROM tbl_transaksi ORDER BY id_transaksi DESC";
            rs = stat.executeQuery(sql);
            while(rs.next()){
                daftartabel.addRow(new Object[]{
                    rs.getInt("id_transaksi"),
                    rs.getString("tgl_transaksi"),
                    rs.getString("total_bayar"),
                    rs.getInt("id_user"),
                    rs.getString("nama_kasir")
                });
            }
        }catch(Exception e){
            System.out.println(e.getMessage());
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        kelola = new javax.swing.JButton();
        loh = new javax.swing.JButton();
        logout = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tanggal_akhir = new com.toedter.calendar.JDateChooser();
        filter = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        list = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        tanggal_awal = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel2.setBackground(new java.awt.Color(153, 204, 255));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/foodxyz/img/icons8-admin-96.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setText("Admin");

        kelola.setBackground(new java.awt.Color(0, 153, 255));
        kelola.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        kelola.setText("Kelola User");
        kelola.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kelolaActionPerformed(evt);
            }
        });

        loh.setBackground(new java.awt.Color(0, 153, 255));
        loh.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        loh.setText("Log Activity");
        loh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lohActionPerformed(evt);
            }
        });

        logout.setBackground(new java.awt.Color(0, 153, 255));
        logout.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        logout.setText("Logout");
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(kelola, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                            .addComponent(logout, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                            .addComponent(loh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(34, 34, 34))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(kelola)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(loh)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(logout)
                .addContainerGap(93, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 180, 380);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setText("Laporan Penjualan");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(310, 10, 240, 36);

        jLabel4.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jLabel4.setText("Tanggal Akhir");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(350, 70, 110, 20);
        getContentPane().add(tanggal_akhir);
        tanggal_akhir.setBounds(350, 100, 130, 22);

        filter.setBackground(new java.awt.Color(0, 153, 255));
        filter.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        filter.setText("Filter");
        filter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filterActionPerformed(evt);
            }
        });
        getContentPane().add(filter);
        filter.setBounds(510, 100, 70, 23);

        list.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(list);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(190, 130, 770, 240);

        jLabel5.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jLabel5.setText("Tanggal Awal");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(200, 70, 110, 20);
        getContentPane().add(tanggal_awal);
        tanggal_awal.setBounds(200, 100, 130, 22);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void kelolaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kelolaActionPerformed
        // TODO add your handling code here:
        adminKelUser halaman = new adminKelUser();
        halaman.setVisible(true);
        this.dispose(); 
    }//GEN-LAST:event_kelolaActionPerformed

    private void lohActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lohActionPerformed
        // TODO add your handling code here:
        adminLogAct halaman = new adminLogAct();
        halaman.setVisible(true);
        this.dispose(); 
    }//GEN-LAST:event_lohActionPerformed

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        // TODO add your handling code here:
        int confirm = JOptionPane.showConfirmDialog(this, "Apakah Anda yakin ingin logout?", "Konfirmasi Logout", JOptionPane.YES_NO_OPTION);
        if (confirm == JOptionPane.YES_OPTION) {
            // Ambil waktu saat ini
            java.util.Date utilDate = new java.util.Date();
            java.sql.Timestamp timestamp = new java.sql.Timestamp(utilDate.getTime());
            java.sql.Date currentDate = new java.sql.Date(new java.util.Date().getTime());

            // Ambil tipe user (contoh: "Admin", "Kasir", dst.) dari sesi login sebelumnya
            String tipeUser = globalaccess.currentUserType;  // Anda harus mengisi kode untuk mengambil tipe user dari sesi login

            // Ambil id_user yang telah login sebelumnya
            int idUser = globalaccess.currentUserId;  // Anda harus mengisi kode untuk mengambil id_user dari sesi login

            String username = globalaccess.currentUsername;

            // Simpan informasi log ke dalam tabel tbl_log
            try {
                FoodXYZ DB = new FoodXYZ();
                DB.konfig();
                Connection kon = DB.con;
                Statement stat = DB.stm;

                String query = "INSERT INTO tbl_log (waktu, tanggal, aktivitas, tipe_user, username, id_user) "
                + "VALUES (?, ?, ?, ?, ?, ?)";

                java.sql.PreparedStatement preparedStatement = kon.prepareStatement(query);
                preparedStatement.setTimestamp(1, timestamp);
                preparedStatement.setDate(2, currentDate);
                preparedStatement.setString(3, "user telah logout");  // Aktivitas logout
                preparedStatement.setString(4, tipeUser);
                preparedStatement.setString(5, username);
                preparedStatement.setInt(6, idUser);

                preparedStatement.executeUpdate();

                // Tampilkan pesan berhasil
                JOptionPane.showMessageDialog(null, "Logout berhasil. Terima kasih!");
                this.dispose();
                new loginForm().setVisible(true);
            } catch (Exception e) {
                // Tampilkan pesan error jika terjadi masalah
                JOptionPane.showMessageDialog(null, "Error saat melakukan logout: " + e.getMessage());
            }
        }
    }//GEN-LAST:event_logoutActionPerformed

    private void filterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filterActionPerformed
        // TODO add your handling code here:
        java.util.Date tanggalAwalDate = tanggal_awal.getDate();
        java.util.Date tanggalAkhirDate = tanggal_akhir.getDate();

        if (tanggalAwalDate != null && tanggalAkhirDate != null) {
            // Konversi tanggal ke format yang cocok dengan database (misal: yyyy-MM-dd)
            java.text.SimpleDateFormat sdf = new java.text.SimpleDateFormat("yyyy-MM-dd");
            String tanggalAwalStr = sdf.format(tanggalAwalDate);
            String tanggalAkhirStr = sdf.format(tanggalAkhirDate);

            // Hapus data tabel sebelumnya
            daftartabel.setRowCount(0);

            // Query untuk mengambil data berdasarkan rentang tanggal
            try {
                sql = "SELECT * FROM tbl_transaksi WHERE tgl_transaksi BETWEEN '" + tanggalAwalStr + "' AND '" + tanggalAkhirStr + "' ORDER BY id_transaksi DESC";
                rs = stat.executeQuery(sql);
                while (rs.next()) {
                    daftartabel.addRow(new Object[]{
                        rs.getInt("id_transaksi"),
                        rs.getString("tgl_transaksi"),
                        rs.getString("total_bayar"),
                        rs.getInt("id_user"),
                        rs.getString("nama_kasir"),
                    });
                }
            } catch (Exception e) {
                System.out.println(e.getMessage());
            }
        } else {
            // Kasih tau user kalau belum pilih tanggal
            JOptionPane.showMessageDialog(null, "Pilih tanggal awal dan tanggal akhir terlebih dahulu!", "Info", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_filterActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(adminLaporan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(adminLaporan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(adminLaporan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(adminLaporan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new adminLaporan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton filter;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton kelola;
    private javax.swing.JTable list;
    private javax.swing.JButton logout;
    private javax.swing.JButton loh;
    private com.toedter.calendar.JDateChooser tanggal_akhir;
    private com.toedter.calendar.JDateChooser tanggal_awal;
    // End of variables declaration//GEN-END:variables
}
