/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package foodxyz;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Adam
 */
public class adminKelUser extends javax.swing.JFrame {

    Statement stat;
    ResultSet rs;
    String sql;
    Connection kon;
    private DefaultTableModel daftartabel;
    
    public adminKelUser() {
        initComponents();
        this.userList();
        FoodXYZ DB = new FoodXYZ();
        DB.konfig();
        kon = DB.con;
        stat = DB.stm;
    }
//    menampilkan data yang ada di tabel user
    public void userList() {
        daftartabel = new DefaultTableModel();
        daftartabel.addColumn("id_user");
        daftartabel.addColumn("tipe user");
        daftartabel.addColumn("nama");
        daftartabel.addColumn("alamat");
        daftartabel.addColumn("telepon");
        daftartabel.addColumn("username");
        daftartabel.addColumn("password");
        list.setModel(daftartabel);
        FoodXYZ user = new FoodXYZ();
        user.konfig();
        kon = user.getConnection();
        try{
            stat = kon.createStatement();
            sql = "SELECT * FROM tbl_user ORDER BY id_user DESC";
            rs = stat.executeQuery(sql);
            while(rs.next()){
                daftartabel.addRow(new Object[]{
                    rs.getInt("id_user"),
                    rs.getString("tipe_user"),
                    rs.getString("nama"),
                    rs.getString("alamat"),
                    rs.getString("telepon"),
                    rs.getString("username"),
                    rs.getString("password")
                });
            }
        }catch(Exception e){
            System.out.println(e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        kelola_laporan = new javax.swing.JButton();
        logout = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        tipeUser = new javax.swing.JComboBox<>();
        password = new javax.swing.JTextField();
        namaUser = new javax.swing.JTextField();
        noTelepon = new javax.swing.JTextField();
        alamat = new javax.swing.JTextField();
        username = new javax.swing.JTextField();
        bHapus = new javax.swing.JButton();
        bTambah = new javax.swing.JButton();
        bEdit = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        list = new javax.swing.JTable();
        iduser = new javax.swing.JTextField();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel2.setBackground(new java.awt.Color(153, 204, 255));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/foodxyz/img/icons8-admin-96.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setText("Admin");

        jButton1.setBackground(new java.awt.Color(0, 153, 255));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1.setText("Log Act");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        kelola_laporan.setBackground(new java.awt.Color(0, 153, 255));
        kelola_laporan.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        kelola_laporan.setText("Kelola Laporan");
        kelola_laporan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kelola_laporanActionPerformed(evt);
            }
        });

        logout.setBackground(new java.awt.Color(0, 153, 255));
        logout.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        logout.setText("Logout");
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(kelola_laporan)
                            .addComponent(logout, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(kelola_laporan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(logout)
                .addContainerGap(234, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 180, 530);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setText("Kelola User");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(340, 10, 160, 36);

        jLabel4.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jLabel4.setText("Password");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(450, 190, 70, 20);

        jLabel5.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jLabel5.setText("Telepon");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(220, 190, 70, 20);

        jLabel6.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jLabel6.setText("Tipe User");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(220, 70, 70, 20);

        jLabel7.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jLabel7.setText("Nama");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(220, 130, 70, 20);

        jLabel8.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jLabel8.setText("Alamat");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(450, 70, 70, 20);

        jLabel9.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jLabel9.setText("Username");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(450, 130, 70, 20);
        getContentPane().add(jLabel10);
        jLabel10.setBounds(450, 280, 0, 0);

        tipeUser.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "gudang", "kasir", "admin" }));
        getContentPane().add(tipeUser);
        tipeUser.setBounds(220, 100, 160, 22);
        getContentPane().add(password);
        password.setBounds(450, 212, 160, 30);
        getContentPane().add(namaUser);
        namaUser.setBounds(220, 152, 160, 30);
        getContentPane().add(noTelepon);
        noTelepon.setBounds(220, 212, 160, 30);
        getContentPane().add(alamat);
        alamat.setBounds(450, 92, 160, 30);
        getContentPane().add(username);
        username.setBounds(450, 152, 160, 30);

        bHapus.setBackground(new java.awt.Color(0, 153, 255));
        bHapus.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        bHapus.setText("Hapus\n");
        bHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bHapusActionPerformed(evt);
            }
        });
        getContentPane().add(bHapus);
        bHapus.setBounds(420, 260, 80, 23);

        bTambah.setBackground(new java.awt.Color(0, 153, 255));
        bTambah.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        bTambah.setText("Tambah");
        bTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bTambahActionPerformed(evt);
            }
        });
        getContentPane().add(bTambah);
        bTambah.setBounds(220, 260, 80, 23);

        bEdit.setBackground(new java.awt.Color(0, 153, 255));
        bEdit.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        bEdit.setText("Edit");
        bEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bEditActionPerformed(evt);
            }
        });
        getContentPane().add(bEdit);
        bEdit.setBounds(320, 260, 80, 23);

        list.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        list.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(list);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(200, 360, 410, 130);

        iduser.setEditable(false);
        getContentPane().add(iduser);
        iduser.setBounds(440, 30, 10, 10);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        adminLogAct halaman = new adminLogAct();
        halaman.setVisible(true);
        this.dispose(); 
    }//GEN-LAST:event_jButton1ActionPerformed
// memeriksa jika semua field sudah diisi
    private boolean isFormValid() {
    if (tipeUser.getSelectedItem().toString().isEmpty() || 
        namaUser.getText().isEmpty() || 
        alamat.getText().isEmpty() || 
        noTelepon.getText().isEmpty() || 
        username.getText().isEmpty() || 
        password.getText().isEmpty()) {
        JOptionPane.showMessageDialog(null, "Semua field harus diisi!", "Error", JOptionPane.ERROR_MESSAGE);
        return false;
    }
    return true;
}
    
    private void bTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bTambahActionPerformed
        // TODO add your handling code here:
        if (!isFormValid()) {
        return;  // Jika form tidak valid, tidak melanjutkan aksi.
        }
        try{
            FoodXYZ user = new FoodXYZ();
            user.konfig();
            kon = user.getConnection();
            sql = "INSERT INTO tbl_user(tipe_user, nama, alamat, telepon, username, password) VALUES(?,?,?,?,?,?)";
            java.sql.PreparedStatement stat = kon.prepareStatement(sql);
            stat.setString(1,(String)tipeUser.getSelectedItem());
            stat.setString(2, namaUser.getText());
            stat.setString(3, alamat.getText());
            stat.setString(4, noTelepon.getText());
            stat.setString(5, username.getText());
            stat.setString(6, password.getText());
            stat.executeUpdate();
            JOptionPane.showMessageDialog(null, "Data Berhasil Masuk", "Chat", JOptionPane.INFORMATION_MESSAGE);
            userList();
        }catch(Exception e) {
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_bTambahActionPerformed

    private void bEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bEditActionPerformed
        // TODO add your handling code here:
        if (!isFormValid()) {
        return;  // Jika form tidak valid, tidak melanjutkan aksi.
        }
        try{
            FoodXYZ list = new FoodXYZ();
            list.konfig();
            kon = list.getConnection();
            java.sql.PreparedStatement stat = kon.prepareStatement("UPDATE tbl_user set tipe_user=?, nama=?, alamat=?, telepon=?, username=?, password=? WHERE id_user=?");
            stat.setString(1, (String) tipeUser.getSelectedItem());
            stat.setString(2, namaUser.getText());
            stat.setString(3,alamat.getText());
            stat.setString(4, noTelepon.getText());
            stat.setString(5, username.getText());
            stat.setString(6, password.getText());
            stat.setString(7, selectedIdUser);
            stat.executeUpdate();
            JOptionPane.showMessageDialog(null, "Data Berhasil Diubah", "Chat", JOptionPane.INFORMATION_MESSAGE);
            userList();
        }catch(Exception e){
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_bEditActionPerformed

    private String selectedIdUser;
    private void listMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listMouseClicked
        // TODO add your handling code here:
        int baris = list.getSelectedRow();
        selectedIdUser = daftartabel.getValueAt(baris, 0).toString();
        tipeUser.setSelectedItem(daftartabel.getValueAt(baris, 1).toString());
        namaUser.setText(daftartabel.getValueAt(baris, 2).toString());
        alamat.setText(daftartabel.getValueAt(baris, 3).toString());
        noTelepon.setText(daftartabel.getValueAt(baris, 4).toString());
        username.setText(daftartabel.getValueAt(baris, 5).toString());
        password.setText(daftartabel.getValueAt(baris, 6).toString());
        
    }//GEN-LAST:event_listMouseClicked

    private void bHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bHapusActionPerformed
        // TODO add your handling code here:
        int confirm = JOptionPane.showConfirmDialog(null, "anda yakin ingin menghapus data ini?", "konfirm", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if(confirm == 0) {
            try{
                 FoodXYZ list = new FoodXYZ();
                 list.konfig();
                 kon = list.getConnection();
                 java.sql.PreparedStatement stat = kon.prepareStatement("DELETE FROM tbl_user WHERE id_user='" + selectedIdUser + "'");
                 stat.executeUpdate();
                 JOptionPane.showMessageDialog(null, "Data berhasil dihapus", "Pesan", JOptionPane.INFORMATION_MESSAGE);
                 userList();
                 tipeUser.setSelectedItem("");
                 namaUser.setText("");
                 noTelepon.setText("");
                 alamat.setText("");
                 username.setText("");
                 password.setText("");
                 iduser.requestFocus();
            }catch(Exception e) {
                JOptionPane.showMessageDialog(null, "Data gagal di hapus" + e.getMessage(), "Pesan", JOptionPane.ERROR_MESSAGE);
            }
        }

    }//GEN-LAST:event_bHapusActionPerformed

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        // TODO add your handling code here:
         int confirm = JOptionPane.showConfirmDialog(this, "Apakah Anda yakin ingin logout?", "Konfirmasi Logout", JOptionPane.YES_NO_OPTION);
        if (confirm == JOptionPane.YES_OPTION) {
         // Ambil waktu saat ini
        java.util.Date utilDate = new java.util.Date();
        java.sql.Timestamp timestamp = new java.sql.Timestamp(utilDate.getTime());
        java.sql.Date currentDate = new java.sql.Date(new java.util.Date().getTime());

        // Ambil tipe user (contoh: "Admin", "Kasir", dst.) dari sesi login sebelumnya
        String tipeUser = globalaccess.currentUserType;  // Anda harus mengisi kode untuk mengambil tipe user dari sesi login

        // Ambil id_user yang telah login sebelumnya
        int idUser = globalaccess.currentUserId;  // Anda harus mengisi kode untuk mengambil id_user dari sesi login
        
        String username = globalaccess.currentUsername;

        // Simpan informasi log ke dalam tabel tbl_log
        try {
            FoodXYZ DB = new FoodXYZ();
            DB.konfig();
            Connection kon = DB.con;
            Statement stat = DB.stm;

            String query = "INSERT INTO tbl_log (waktu, tanggal, aktivitas, tipe_user, username, id_user) "
                         + "VALUES (?, ?, ?, ?, ?, ?)";

            java.sql.PreparedStatement preparedStatement = kon.prepareStatement(query);
            preparedStatement.setTimestamp(1, timestamp);
            preparedStatement.setDate(2, currentDate);
            preparedStatement.setString(3, "user telah logout");  // Aktivitas logout
            preparedStatement.setString(4, tipeUser);
            preparedStatement.setString(5, username);
            preparedStatement.setInt(6, idUser);

            preparedStatement.executeUpdate();

            // Tampilkan pesan berhasil
            JOptionPane.showMessageDialog(null, "Logout berhasil. Terima kasih!");
            this.dispose();
            new loginForm().setVisible(true);
        } catch (Exception e) {
            // Tampilkan pesan error jika terjadi masalah
            JOptionPane.showMessageDialog(null, "Error saat melakukan logout: " + e.getMessage());
        }
        }
    }//GEN-LAST:event_logoutActionPerformed

    private void kelola_laporanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kelola_laporanActionPerformed
        // TODO add your handling code here:
        adminLaporan halaman = new adminLaporan();
        halaman.setVisible(true);
        this.dispose(); 
    }//GEN-LAST:event_kelola_laporanActionPerformed

    

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(adminKelUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(adminKelUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(adminKelUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(adminKelUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new adminKelUser().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField alamat;
    private javax.swing.JButton bEdit;
    private javax.swing.JButton bHapus;
    private javax.swing.JButton bTambah;
    private javax.swing.JTextField iduser;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton kelola_laporan;
    private javax.swing.JTable list;
    private javax.swing.JButton logout;
    private javax.swing.JTextField namaUser;
    private javax.swing.JTextField noTelepon;
    private javax.swing.JTextField password;
    private javax.swing.JComboBox<String> tipeUser;
    private javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables
}
