/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package foodxyz;

import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Adam
 */
public class adminLogAct extends javax.swing.JFrame {

    Statement stat;
    ResultSet rs;
    String sql;
    Connection kon;
    private DefaultTableModel daftartabel;
    public adminLogAct() {
        initComponents();
        this.listLog();
        FoodXYZ DB = new FoodXYZ();
        DB.konfig();
        kon = DB.con;
        stat = DB.stm;
    }
//    menampilkan data yang ada di tabel log
    public void listLog() {
        daftartabel = new DefaultTableModel();
        daftartabel.addColumn("id");
        daftartabel.addColumn("waktu");
        daftartabel.addColumn("tanggal");
        daftartabel.addColumn("aktivitas");
        daftartabel.addColumn("tipe user");
        daftartabel.addColumn("username");
        daftartabel.addColumn("id_user");
        list.setModel(daftartabel);
        FoodXYZ list = new FoodXYZ();
        list.konfig(); 
        Connection kon = list.getConnection(); 
        try{
            stat = kon.createStatement();
            sql = "SELECT * FROM tbl_log ORDER BY id_log DESC";
            rs = stat.executeQuery(sql);
            while(rs.next()){
                daftartabel.addRow(new Object[]{
                    rs.getInt("id_log"),
                    rs.getString("waktu"),
                    rs.getString("tanggal"),
                    rs.getString("aktivitas"),
                    rs.getString("tipe_user"),
                    rs.getString("username"),
                    rs.getInt("id_user"),
                });
            }
        }catch(Exception e){
            System.out.println(e.getMessage());
        }
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        kelola = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        logout = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tanggal_filter = new com.toedter.calendar.JDateChooser();
        filter = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        list = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel2.setBackground(new java.awt.Color(153, 204, 255));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/foodxyz/img/icons8-admin-96.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setText("Admin");

        kelola.setBackground(new java.awt.Color(0, 153, 255));
        kelola.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        kelola.setText("Kelola User");
        kelola.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kelolaActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(0, 153, 255));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton2.setText("Kelola Laporan");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        logout.setBackground(new java.awt.Color(0, 153, 255));
        logout.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        logout.setText("Logout");
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(kelola, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2)
                            .addComponent(logout, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(kelola)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(logout)
                .addContainerGap(93, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 180, 380);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setText("Log Activity");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(340, 10, 160, 36);

        jLabel4.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jLabel4.setText("Pilih Tanggal");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(200, 70, 70, 20);
        getContentPane().add(tanggal_filter);
        tanggal_filter.setBounds(200, 100, 190, 22);

        filter.setBackground(new java.awt.Color(0, 153, 255));
        filter.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        filter.setText("Filter");
        filter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filterActionPerformed(evt);
            }
        });
        getContentPane().add(filter);
        filter.setBounds(410, 100, 70, 23);

        list.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(list);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(190, 130, 770, 240);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void kelolaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kelolaActionPerformed
        // TODO add your handling code here:
           adminKelUser halaman = new adminKelUser();
           halaman.setVisible(true);
           this.dispose();
    }//GEN-LAST:event_kelolaActionPerformed

    private void filterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filterActionPerformed
        // TODO add your handling code here:
        java.util.Date tanggalFilter = tanggal_filter.getDate();
        if (tanggalFilter != null) {
            // Konversi tanggal ke format yang cocok dengan database (misal: yyyy-MM-dd)
            java.text.SimpleDateFormat sdf = new java.text.SimpleDateFormat("yyyy-MM-dd");
            String tanggalFilterStr = sdf.format(tanggalFilter);

            // Hapus data tabel sebelumnya
            daftartabel.setRowCount(0);

            // Query untuk mengambil data berdasarkan tanggal filter
            try {
                sql = "SELECT * FROM tbl_log WHERE tanggal = '" + tanggalFilterStr + "' ORDER BY id_log DESC";
                rs = stat.executeQuery(sql);
                while (rs.next()) {
                    daftartabel.addRow(new Object[]{
                        rs.getInt("id_log"),
                        rs.getString("waktu"),
                        rs.getString("tanggal"),
                        rs.getString("aktivitas"),
                        rs.getString("tipe_user"),
                        rs.getString("username"),
                        rs.getInt("id_user"),
                    });
                }
            } catch (Exception e) {
                System.out.println(e.getMessage());
            }
        } else {
            // Kasih tau user kalau belum pilih tanggal
            JOptionPane.showMessageDialog(null, "Pilih tanggal dulu, ya!", "Info", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_filterActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        adminLaporan halaman = new adminLaporan();
        halaman.setVisible(true);
        this.dispose(); 
    }//GEN-LAST:event_jButton2ActionPerformed

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        // TODO add your handling code here:
        int confirm = JOptionPane.showConfirmDialog(this, "Apakah Anda yakin ingin logout?", "Konfirmasi Logout", JOptionPane.YES_NO_OPTION);
        if (confirm == JOptionPane.YES_OPTION) {
         // Ambil waktu saat ini
        java.util.Date utilDate = new java.util.Date();
        java.sql.Timestamp timestamp = new java.sql.Timestamp(utilDate.getTime());
        java.sql.Date currentDate = new java.sql.Date(new java.util.Date().getTime());

        // Ambil tipe user (contoh: "Admin", "Kasir", dst.) dari sesi login sebelumnya
        String tipeUser = globalaccess.currentUserType;  // Anda harus mengisi kode untuk mengambil tipe user dari sesi login

        // Ambil id_user yang telah login sebelumnya
        int idUser = globalaccess.currentUserId;  // Anda harus mengisi kode untuk mengambil id_user dari sesi login
        
        String username = globalaccess.currentUsername;

        // Simpan informasi log ke dalam tabel tbl_log
        try {
            FoodXYZ DB = new FoodXYZ();
            DB.konfig();
            Connection kon = DB.con;
            Statement stat = DB.stm;

            String query = "INSERT INTO tbl_log (waktu, tanggal, aktivitas, tipe_user, username, id_user) "
                         + "VALUES (?, ?, ?, ?, ?, ?)";

            java.sql.PreparedStatement preparedStatement = kon.prepareStatement(query);
            preparedStatement.setTimestamp(1, timestamp);
            preparedStatement.setDate(2, currentDate);
            preparedStatement.setString(3, "user telah logout");  // Aktivitas logout
            preparedStatement.setString(4, tipeUser);
            preparedStatement.setString(5, username);
            preparedStatement.setInt(6, idUser);

            preparedStatement.executeUpdate();

            // Tampilkan pesan berhasil
            JOptionPane.showMessageDialog(null, "Logout berhasil. Terima kasih!");
            this.dispose();
            new loginForm().setVisible(true);
        } catch (Exception e) {
            // Tampilkan pesan error jika terjadi masalah
            JOptionPane.showMessageDialog(null, "Error saat melakukan logout: " + e.getMessage());
        }
        }
    }//GEN-LAST:event_logoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(adminLogAct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(adminLogAct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(adminLogAct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(adminLogAct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new adminLogAct().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton filter;
    private javax.swing.JButton jButton2;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton kelola;
    private javax.swing.JTable list;
    private javax.swing.JButton logout;
    private com.toedter.calendar.JDateChooser tanggal_filter;
    // End of variables declaration//GEN-END:variables
}
