/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package foodxyz;

import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
/**
 *
 * @author Adam
 */
public class loginForm extends javax.swing.JFrame {
 // deklarasi
    Connection konn;
    Statement stat;
    ResultSet rs;
    String sql;
    /**
     * Creates new form loginForm
     */
    public loginForm() {
        initComponents();
        FoodXYZ DB = new FoodXYZ();
        DB.konfig();
        konn = DB.con;
        stat = DB.stm;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        username = new javax.swing.JTextField();
        reset = new javax.swing.JButton();
        login = new javax.swing.JButton();
        password = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/foodxyz/img/icons8-shop-96.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(250, 20, 100, 90);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setText("Food XYZ");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(240, 110, 110, 40);

        username.setFont(new java.awt.Font("Lucida Sans Unicode", 1, 12)); // NOI18N
        username.setText("Username");
        username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameActionPerformed(evt);
            }
        });
        getContentPane().add(username);
        username.setBounds(200, 190, 200, 30);

        reset.setBackground(new java.awt.Color(204, 204, 204));
        reset.setText("Reset");
        getContentPane().add(reset);
        reset.setBounds(310, 290, 90, 30);

        login.setBackground(new java.awt.Color(102, 204, 255));
        login.setText("Login");
        login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginActionPerformed(evt);
            }
        });
        getContentPane().add(login);
        login.setBounds(200, 290, 90, 30);

        password.setText("jPasswordField1");
        password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordActionPerformed(evt);
            }
        });
        getContentPane().add(password);
        password.setBounds(200, 250, 200, 30);

        jLabel3.setText("PASSWORD");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(200, 230, 70, 16);

        jLabel4.setText("USERNAME");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(200, 170, 70, 16);

        pack();
    }// </editor-fold>//GEN-END:initComponents

//    membuat fungsi untuk memasukkan data user yang login ke tabel log
//    menerima paramater id user, tipe user, dan username
    private void logLoginActivity(String userId, String tipeUser, String username) {
        try {
            String logSql = "INSERT INTO tbl_log (waktu, tanggal, aktivitas, tipe_user, username, id_user) VALUES (?, ?, ?, ?, ?, ?)";
            java.sql.Timestamp timestamp = new java.sql.Timestamp(new java.util.Date().getTime());
            java.sql.Date currentDate = new java.sql.Date(new java.util.Date().getTime());
            java.sql.PreparedStatement pstmt = konn.prepareStatement(logSql);
            pstmt.setTimestamp(1, timestamp);
            pstmt.setDate(2, currentDate);
            pstmt.setString(3, "user telah login");
            pstmt.setString(4, tipeUser);
            pstmt.setString(5, username);
            pstmt.setString(6, userId);
            pstmt.executeUpdate();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error while logging activity: " + e.getMessage());
        }
}
    private void loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginActionPerformed
       try{
        sql = "SELECT * FROM tbl_user WHERE username='" + username.getText()+"' AND password='" + password.getText()+"'";
        rs = stat.executeQuery(sql);
        if(rs.next()){
                if(username.getText().equals(rs.getString("username")) && password.getText().equals(rs.getString("password"))){
                String tipeUser = rs.getString("tipe_user");
                    switch (tipeUser) {
                        case "gudang":
                            new gudangKelolaBarang().setVisible(true);
                            break;
                        case "kasir":
                            new kasirKelTransaksi().setVisible(true);
                            break;
                        case "admin":
                            new adminLogAct().setVisible(true);
                            break;
                        default:
                            JOptionPane.showMessageDialog(null, "username atau password anda salah");
                            break;
                    }
                     // Mengambil nama pengguna saat ini dari sesi
                    String currentUsername = sesiKasir.getCurrentName();
                    System.out.println("Nama pengguna saat ini: " + currentUsername);

//                    mengirim parameter ke fungsi logloginactivity
                    logLoginActivity(rs.getString("id_user"), rs.getString("tipe_user"), rs.getString("username"));
//                    menyimpan data user yang sedang login ke class baru
                    globalaccess.currentUserType = rs.getString("tipe_user");
                    globalaccess.currentUsername = rs.getString("username");
                    globalaccess.currentUserId = rs.getInt("id_user");  // Contoh id_user
                    globalaccess.currentName = rs.getString("nama");
            }
        }else {
            JOptionPane.showMessageDialog(null, "username atau password salah");
        }
   }
   catch(Exception e){
       JOptionPane.showMessageDialog(this, e.getMessage());
   }
    this.dispose();   
    }//GEN-LAST:event_loginActionPerformed

    private void usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameActionPerformed

    private void passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(loginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(loginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(loginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(loginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new loginForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton login;
    private javax.swing.JPasswordField password;
    private javax.swing.JButton reset;
    private javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables
}
